base_url = "https://no-bull.sh"

title = "no bull.sh"
default_language = "en"

compile_sass = true
build_search_index = true
minify_html = true

generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown.highlighting]
error_on_missing_language = true
style = "inline"
theme = "github-dark"

[extra]
site_name = "no bull.sh"
