# On every push this script is executed
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Rebuild at 12 Midnight every day
  schedule:
    - cron: '0 0 * * *'

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      # Build sponsors image
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
      - run: npm ci
      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: james7132
      - run: mv sponsorkit/sponsors.svg content

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
